### ISSUE TITLE
output github commit url on fixed bugs?

### ISSUE THREAD

**Issue by h0lzi** [bahamat/jinni#3]
Not sure how much overhead this creates. But I think it would be nice to have the bot output the commit github url if the bug is fixed and if not fixed yet mention that also

**Comment by bahamat** [comment]
This would involve significant overhead for bugview issues. Bugview has API access to our jira, but jinni does not. It only checks the HTTP response code to determine if a bug is public, private, or invalid. Jinni, by design, operates purely on public, non-privileged data. It doesn't even use a github API key.

Being able to fetch the commit for bugview issues would require parsing the HTML and would be quite error prone. I think it's easy enough for people to click the link and see the issue details, including the commits.
